// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBVZf39i0i5OS4todz0H62pOL8DahfiNp4',
//     appId: '1:963114560417:android:1c889c7fa8822d1cf139e0',
//     messagingSenderId: '963114560417',
//     projectId: 'rti-app-ac7b6',
//     databaseURL: 'https://rti-app-ac7b6-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rti-app-ac7b6.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDlBq6LTT4r5d2bkbh7wHf4V2qi4FcHP0o',
//     appId: '1:963114560417:ios:cb89b9fc2e2ea29cf139e0',
//     messagingSenderId: '963114560417',
//     projectId: 'rti-app-ac7b6',
//     databaseURL: 'https://rti-app-ac7b6-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'rti-app-ac7b6.appspot.com',
//     iosBundleId: 'com.telangana.rti.rtiTelangana',
//   );
//
// }